// Generated by CoffeeScript 1.12.6
var adminLoggedIn, apiOffline, loadNavbar, teacherLoggedIn, teacherLoggedInNoCompetition, userLoggedIn, userLoggedInNoCompetition, userNotLoggedIn;

apiOffline = {
  Login: "/login",
  News: "/news",
  About: "/about",
  Rules: "/rules"
};

teacherLoggedIn = {
  Problems: "/problems",
  Scoreboard: "/scoreboard",
  News: "/news",
  About: "/about",
  Rules: "/rules"
};

teacherLoggedInNoCompetition = {
  News: "/news",
  About: "/about",
  Rules: "/rules"
};

userLoggedIn = {
  Problems: "/problems",
  Scoreboard: "/scoreboard",
  News: "/news",
  About: "/about",
  Rules: "/rules"
};

userLoggedInNoCompetition = {
  Scoreboard: "/scoreboard",
  News: "/news",
  About: "/about",
  Rules: "/rules"
};

userNotLoggedIn = {
  Login: "/login",
  News: "/news",
  About: "/about",
  Rules: "/rules"
};

adminLoggedIn = {
  Management: "/management"
};

loadNavbar = function(renderNavbarLinks, renderNestedNavbarLinks) {
  var navbarLayout;
  navbarLayout = {
    renderNavbarLinks: renderNavbarLinks,
    renderNestedNavbarLinks: renderNestedNavbarLinks
  };
  return apiCall("GET", "/api/user/status", {}).done(function(data) {
    navbarLayout.links = userNotLoggedIn;
    navbarLayout.status = data.data;
    navbarLayout.topLevel = true;
    if (data["status"] === 1) {
      if (!data.data["logged_in"]) {
        $(".show-when-logged-out").css("display", "inline-block");
      }
      if (data.data["teacher"]) {
        if (data.data["competition_active"]) {
          navbarLayout.links = teacherLoggedIn;
        } else {
          navbarLayout.links = teacherLoggedInNoCompetition;
        }
      } else if (data.data["logged_in"]) {
        if (data.data["competition_active"]) {
          navbarLayout.links = userLoggedIn;
        } else {
          navbarLayout.links = userLoggedInNoCompetition;
        }
      }
      if (data.data["admin"]) {
        $.extend(navbarLayout.links, adminLoggedIn);
      }
    }
    $("#navbar-links").html(renderNavbarLinks(navbarLayout));
    return $("#navbar-item-logout").on("click", logout);
  }).fail(function() {
    navbarLayout.links = apiOffline;
    return $("#navbar-links").html(renderNavbarLinks(navbarLayout));
  });
};

$(function() {
  var renderNavbarLinks, renderNestedNavbarLinks;
  renderNavbarLinks = _.template($("#navbar-links-template").remove().text());
  renderNestedNavbarLinks = _.template($("#navbar-links-dropdown-template").remove().text());
  return loadNavbar(renderNavbarLinks, renderNestedNavbarLinks);
});
